language: java

before_install:
    - rvm install 2.3.1
    - gem install asciidoctor
    - asciidoctor --version
    - git clone https://github.com/asciidoctor/asciidoctor-fopub

script: ./travis_make.sh
      
